package observatory

/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'ane' at '11/14/16 6:22 PM' with Gradle 3.2
 *
 * @author ane, @date 11/14/16 6:22 PM
 */

import org.junit.runner.RunWith
import org.scalatest.FunSuite
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod bibba is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
