package observatory

/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'ane' at '11/14/16 6:22 PM' with Gradle 3.2
 *
 * @author ane, @date 11/14/16 6:22 PM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
